gadmin config set Admin.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set Admin.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set Admin.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set Admin.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set Controller.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set Controller.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set Controller.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set Controller.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set Dict.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set Dict.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set Dict.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set ETCD.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set ETCD.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set ETCD.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set ETCD.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set Executor.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set Executor.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set Executor.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set Executor.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set FileLoader.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set FileLoader.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set FileLoader.BasicConfig.LogConfig.LogLevel OFF
gadmin config set FileLoader.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set GPE.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set GPE.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set GPE.BasicConfig.LogConfig.LogLevel OFF
gadmin config set GPE.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set GSE.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set GSE.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set GSE.BasicConfig.LogConfig.LogLevel OFF
gadmin config set GSE.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set GSQL.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set GSQL.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set GSQL.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set GSQL.CatalogBackupFileMaxDurationDay 5
gadmin config set GSQL.CatalogBackupFileMaxNumber 10
gadmin config set GSQL.QueryResponseMaxSizeByte 67108864
gadmin config set GUI.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set GUI.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set GUI.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set GUI.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set Informant.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set Informant.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set Informant.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set Informant.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set Kafka.RetentionHours 12
gadmin config set Kafka.RetentionSizeGB 5
gadmin config set Kafka.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set Kafka.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set Kafka.BasicConfig.LogConfig.LogRotationFileNumber 7
gadmin config set KafkaConnect.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set KafkaConnect.BasicConfig.LogConfig.LogLevel ERROR
gadmin config set KafkaConnect.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set KafkaLoader.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set KafkaLoader.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set KafkaLoader.BasicConfig.LogConfig.LogLevel OFF
gadmin config set KafkaLoader.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set KafkaStreamLL.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set KafkaStreamLL.BasicConfig.LogConfig.LogLevel OFF
gadmin config set KafkaStreamLL.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set Nginx.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set Nginx.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set Nginx.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set RESTPP.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set RESTPP.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set RESTPP.BasicConfig.LogConfig.LogLevel BRIEF
gadmin config set RESTPP.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set RESTPP.Factory.DefaultQueryTimeoutSec 90
gadmin config set RESTPP.Factory.StatsIntervalSec 120
gadmin config set TS3.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set TS3.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set TS3.BasicConfig.LogConfig.LogLevel FATAL
gadmin config set TS3.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set TS3.RetentionPeriodDay 7
gadmin config set TS3Server.BasicConfig.LogConfig.LogFileMaxDurationDay 7
gadmin config set TS3Server.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set TS3Server.BasicConfig.LogConfig.LogLevel FATAL
gadmin config set TS3Server.BasicConfig.LogConfig.LogRotationFileNumber 5
gadmin config set ZK.BasicConfig.LogConfig.LogFileMaxSizeMB 50
gadmin config set ZK.BasicConfig.LogConfig.LogLevel OFF
gadmin config set ZK.BasicConfig.LogConfig.LogRotationFileNumber 5


gadmin config set Nginx.ClientMaxBodySize 1024
gadmin config set Nginx.WorkerProcessNumber 1
gadmin config set GPE.Kafka.CompressCodec gzip
