version: "3.8"
services:
  tgente3:
    image: "xpertmind/tigergraph:free_latest"
    container_name: tgente3
    restart: unless-stopped
    ports:
      - '9003:9000'
      - '2022:22'
      - '14243:14240'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - ./tigergraph/scripts:/home/tigergraph/scripts
      - ./tigergraph/log:/opt/tigergraph/log
      - ./tigergraph/data:/opt/tigergraph/data
    stdin_open: true
    tty: true
